// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace parksapifullstack.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20200512182857_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Campgrounds");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("ClimbingRoutes");

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<int>("GeneralStores");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 2,
                            Campgrounds = 3,
                            City = "Three Rivers",
                            ClimbingRoutes = 1,
                            Description = "It's ancient",
                            GeneralStores = 4,
                            Name = "Sequoia National Park",
                            State = "CA"
                        },
                        new
                        {
                            ParkId = 3,
                            Campgrounds = 9,
                            City = "Yosemite National Park",
                            ClimbingRoutes = 1348,
                            Description = "I met my friend Sam here",
                            GeneralStores = 8,
                            Name = "Yosemite National Park",
                            State = "CA"
                        },
                        new
                        {
                            ParkId = 4,
                            Campgrounds = 4,
                            City = "Grand Canyon",
                            ClimbingRoutes = 46,
                            Description = "It big",
                            GeneralStores = 3,
                            Name = "Grand Canyon National Park",
                            State = "AZ"
                        },
                        new
                        {
                            ParkId = 5,
                            Campgrounds = 17,
                            City = "Glacier",
                            ClimbingRoutes = 5,
                            Description = "I didn't get to see it 'cause Donald shut down the government when I got there, whatta loon.",
                            GeneralStores = 1,
                            Name = "Glacier National Park",
                            State = "MT"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
